entries_list = [
    1, 10, 25, 50, 100
]

fur = {
    "red": "Russet",
    "orange": "Orange",
    "pale": "Pale Ginger",
    "yellow": "Yellow",
    "cream": "Cream",
    "white": "White",
    "grey": "Grey",
    "black": "Black",
    "brown": "Brown",
    "tortoise": "Tortoiseshell",
    "calico": "Calico"
}

descriptors = {
    "cute": "Cute",
    "edgy": "Edgy",
    "nature": "Nature-themed",
    "powerful": "Powerful",
    "pretty": "Pretty"
}

clans = {
    "river": "RiverClan",
    "shadow": "ShadowClan",
    "thunder": "ThunderClan",
    "wind": "WindClan"
}

names_prefix = {
        "Fire": ["general", "edgy", "nature", "powerful", "orange", "red", "yellow"],
        "Squirrel": ["general", "nature", "orange", "red", "brown", "cream"],
        "Bramble": ["general", "nature", "powerful", "brown", "pale"],
        "Flame": ["general", "edgy", "nature", "powerful", "orange", "red", "yellow"],
        "Ash": ["general", "edgy", "nature", "grey", "black", "pale"],
        "Tiger": ["general", "edgy", "powerful", "orange", "brown", "red",],
        "Acorn": ["general", "nature", "orange", "red", "yellow", "cream", "pale", "brown"],
        "Adder": ["general", "edgy", "nature", "powerful"],
        "Alder": ["general", "nature"],
        "Amber": ["general" "orange", "red", "brown", "cream", "pale", "tortoise"],
        "Ant": ["general", "edgy", "nature"],
        "Apple": ["general", "nature"],
        "Arch": ["general"],
        "Aspen": ["general", "nature"],
        "Badger": ["general", "nature", "powerful", "grey", "black", "white"],
        "Bark": ["general", "nature", "brown", "pale", "tortoise"],
        "Barley": ["general", "nature"],
        "Bay": ["general", "nature"],
        "Bee": ["general", "nature"],
        "Beech": ["general", "nature"],
        "Beetle": ["general", "edgy", "nature", "black", "brown", "tortoise"],
        "Berry": ["general", "nature"],
        "Big": ["general", "powerful"],
        "Birch": ["general", "nature", "brown", "cream", "pale", "tortoise"],
        "Bird": ["general", "nature"],
        "Black": ["general", "edgy", "black"],
        "Blizzard": ["general", "edgy", "powerful", "white"],
        "Bloom": ["general", "nature"],
        "Blossom": ["general", "nature"],
        "Blue": ["general", "grey"],
        "Bluebell": ["general", "nature"],
        "Boulder": ["general", "nature", "powerful", "black", "grey"],
        "Bounce": ["general"],
        "Brave": ["general", "powerful"],
        "Breeze": ["general", "nature"],
        "Briar": ["general", "nature"],
        "Bright": ["general"],
        "Brindle": ["general", "tortoise", "calico"],
        "Bristle": ["general", "edgy", "powerful"],
        "Broken": ["general", "edgy"],
        "Brown": ["general", "brown", "cream", "tortoise"],
        "Bubble": ["general", "nature"],
        "Bumble": ["general", "nature"],
        "Bunny": ["general", "nature"],
        "Burr": ["general", "edgy", "nature"],
        "Buttercup": ["general", "nature"],
        "Buzzard": ["general", "edgy", "nature"],
        "Cedar": ["general", "nature", "powerful"],
        "Cherry": ["general", "nature", "red", "pale", "cream"],
        "Chestnut": ["general", "nature", "brown", "cream", "tortoise"],
        "Chive": ["general", "nature"],
        "Cinder": ["general", "edgy", "nature", "grey", "black"],
        "Cinnamon": ["general", "nature", "red", "orange", "pale", "brown"],
        "Claw": ["general", "powerful"],
        "Cloud": ["general", "nature", "white"],
        "Clover": ["general", "nature"],
        "Coal": ["general", "edgy", "nature", "black", "grey"],
        "Copper": ["general", "red", "orange", "pale"],
        "Coriander": ["general", "nature"],
        "Creek": ["general", "nature"],
        "Cricket": ["general", "nature"],
        "Crooked": ["general", "edgy"],
        "Crouch": ["general"],
        "Crow": ["general", "edgy", "nature", "grey", "black"],
        "Curl": ["general"],
        "Curly": ["general"],
        "Cypress": ["general", "nature"],
        "Daffodil": ["general", "nature", "yellow", "pale", "white", "cream"],
        "Daisy": ["general", "nature", "yellow", "pale", "white", "cream"],
        "Dandelion": ["general", "nature", "yellow", "pale", "white", "cream"],
        "Dapple": ["general", "tortoise"],
        "Dark": ["general", "edgy", "black", "grey"],
        "Dart": ["general"],
        "Dawn": ["general", "nature", "cream", "pale", "yellow", "white"],
        "Deer": ["general", "nature", "red", "brown", "cream", "pale", "orange"],
        "Dew": ["general", "nature"],
        "Doe": ["general", "nature", "red", "brown", "cream", "pale", "orange"],
        "Dove": ["general", "nature", "white", "grey", "pale"],
        "Drift": ["general"],
        "Drizzle": ["general", "nature", "grey"],
        "Dusk": ["general", "edgy", "black", "grey"],
        "Duck": ["general", "nature"],
        "Eagle": ["general", "nature", "powerful"],
        "Echo": ["general", "edgy"],
        "Eel": ["general", "edgy", "nature"],
        "Ember": ["general", "edgy", "nature", "black", "red", "grey", "brown", "calico"],
        "Falcon": ["general", "edgy", "nature", "powerful"],
        "Fall": ["general"],
        "Fallen": ["general", "edgy", "powerful"],
        "Falling": ["general", "edgy"],
        "Fallow": ["general"],
        "Fawn": ["general", "nature", "red", "brown", "cream", "pale", "orange"],
        "Feather": ["general", "nature"],
        "Fennel": ["general", "nature"],
        "Fern": ["general", "nature"],
        "Fidget": ["general"],
        "Fierce": ["general", "edgy", "powerful"],
        "Finch": ["general", "nature"],
        "Fin": ["general", "nature"],
        "Fir": ["general", "nature", "powerful"],
        "Fish": ["general", "nature"],
        "Flail": ["general"],
        "Flash": ["general", "powerful"],
        "Flax": ["general", "nature"],
        "Fleck": ["general"],
        "Fleet": ["general", "powerful"],
        "Flick": ["general"],
        "Flicker": ["general"],
        "Flight": ["general"],
        "Flint": ["general", "powerful", "black", "grey"],
        "Flip": ["general"],
        "Flora": ["general", "nature"],
        "Flower": ["general", "nature"],
        "Flurry": ["general", "nature"],
        "Flutter": ["general"],
        "Fly": ["general", "edgy", "nature"],
        "Fog": ["general", "edgy", "nature", "grey"],
        "Foggy": ["general", "nature", "grey"],
        "Fox": ["general", "edgy", "nature"],
        "Freckle": ["general", "tortoise", "calico"],
        "Frog": ["general", "nature"],
        "Frond": ["general", "nature"],
        "Frost": ["general", "nature", "white", "grey", "pale"],
        "Furl": ["general"],
        "Fuzz": ["general"],
        "Fuzzy": ["general"],
        "Golden": ["general", "yellow", "cream", "pale"],
        "Goose": ["general", "nature"],
        "Gorse": ["general", "nature"],
        "Grass": ["general", "nature"],
        "Gray": ["general", "grey"],
        "Gull": ["general", "nature"],
        "Hail": ["general", "nature", "powerful", "white"],
        "Half": ["general"],
        "Hare": ["general", "nature"],
        "Hatch": ["general"],
        "Haven": ["general"],
        "Hawk": ["general", "edgy", "nature", "powerful"],
        "Hay": ["general", "nature"],
        "Haze": ["general", "nature", "white", "grey"],
        "Hazel": ["general", "nature"],
        "Heather": ["general", "nature"],
        "Heron": ["general", "nature", "powerful"],
        "Hickory": ["general", "nature"],
        "Hill": ["general", "nature"],
        "Hollow": ["general", "edgy", "nature"],
        "Honey": ["general", "nature", "yellow", "pale"],
        "Hoot": ["general", "nature"],
        "Hope": ["general"],
        "Hop": ["general"],
        "Hound": ["general", "edgy", "nature"],
        "Ice": ["general", "edgy", "nature", "white"],
        "Ivy": ["general", "nature"],
        "Jagged": ["general", "edgy", "powerful"],
        "Jay": ["general", "nature"],
        "Jump": ["general", "powerful"],
        "Juniper": ["general", "edgy", "nature"],
        "Kestrel": ["general", "nature"],
        "Kite": ["general", "nature"],
        "Lake": ["general", "nature"],
        "Larch": ["general", "nature"],
        "Lark": ["general", "nature"],
        "Lavender": ["general", "nature"],
        "Leaf": ["general", "nature"],
        "Leopard": ["general", "edgy", "nature", "powerful"],
        "Lichen": ["general", "edgy", "nature"],
        "Light": ["general", "white", "cream", "pale"],
        "Lightning": ["general", "edgy", "nature", "powerful"],
        "Lily": ["general", "nature"],
        "Lion": ["general", "edgy", "nature", "powerful", "yellow", "pale", "orange", "red", "brown"],
        "Little": ["general"],
        "Lizard": ["general", "edgy", "nature"],
        "Log": ["general", "nature"],
        "Long": ["general"],
        "Loud": ["general", "powerful"],
        "Low": ["general"],
        "Lynx": ["general", "edgy", "nature"],
        "Maggot": ["general", "edgy", "nature"],
        "Magpie": ["general", "nature", "black", "white"],
        "Mallow": ["general", "nature"],
        "Maple": ["general", "nature", "powerful", "calico", "tortoise", "brown", "red", "orange"],
        "Marigold": ["general", "nature", "yellow", "orange", "pale"],
        "Marsh": ["general", "edgy", "nature"],
        "Meadow": ["general", "nature"],
        "Merry": ["general"],
        "Midge": ["general", "edgy", "nature"],
        "Milk": ["general", "nature", "white", "pale"],
        "Minnow": ["general", "nature"],
        "Mint": ["general", "nature"],
        "Mist": ["general", "edgy", "nature"],
        "Misty": ["general", "nature"],
        "Mole": ["general", "edgy", "nature", "brown", "grey", "black"],
        "Moon": ["general", "edgy", "nature"],
        "Morning": ["general", "nature"],
        "Moss": ["general", "nature"],
        "Moth": ["general", "nature"],
        "Mottle": ["general", "edgy", "tortoise", "calico"],
        "Mouse": ["general", "nature"],
        "Mud": ["general", "edgy", "nature", "brown", "red"],
        "Muddy": ["general", "nature", "brown", "red"],
        "Myrtle": ["general", "nature"],
        "Nectar": ["general", "nature"],
        "Needle": ["general", "edgy", "powerful"],
        "Nettle": ["general", "edgy", "nature"],
        "Dock": ["general", "nature"],
        "Newt": ["general", "edgy", "nature"],
        "Night": ["general", "edgy", "nature", "powerful", "black", "grey"],
        "Nutmeg": ["general", "nature", "brown", "cream", "pale"],
        "Nut": ["general", "nature", "brown", "cream", "pale"],
        "Oak": ["general", "nature", "powerful", "brown", "black", "grey"],
        "Oat": ["general", "nature", "brown", "pale", "cream"],
        "Olive": ["general", "nature"],
        "One": ["general"],
        "Otter": ["general", "nature", "brown", "red"],
        "Owl": ["general", "edgy", "nature"],
        "Pale": ["general", "edgy", "pale", "cream", "white"],
        "Parsley": ["general", "nature"],
        "Parsnip": ["general", "nature"],
        "Patch": ["general", "tortoise", "calico"],
        "Pear": ["general", "nature"],
        "Pebble": ["general", "nature"],
        "Pepper": ["general", "nature"],
        "Perch": ["general", "nature"],
        "Petal": ["general", "nature"],
        "Pigeon": ["general", "nature", "grey", "brown"],
        "Pike": ["general", "nature", "powerful"],
        "Pine": ["general", "nature"],
        "Pink": ["general"],
        "Plum": ["general", "nature"],
        "Pool": ["general", "nature"],
        "Poppy": ["general", "nature"],
        "Pounce": ["general"],
        "Prickle": ["general", "nature"],
        "Primrose": ["general", "nature"],
        "Puddle": ["general", "nature"],
        "Pumpkin": ["general", "nature", "orange", "red", "yellow"],
        "Quail": ["general", "nature"],
        "Quick": ["general", "powerful"],
        "Quiet": ["general"],
        "Rabbit": ["general", "nature"],
        "Ragged": ["general", "edgy"],
        "Rain": ["general", "nature"],
        "Rat": ["general", "edgy", "nature"],
        "Raven": ["general", "edgy", "nature", "black", "grey"],
        "Red": ["general", "red", "orange", "brown"],
        "Reed": ["general", "nature"],
        "Ripple": ["general", "nature"],
        "Rising": ["general"],
        "River": ["general", "nature"],
        "Roach": ["general", "edgy", "nature", "brown", "black", "grey"],
        "Robin": ["general", "nature"],
        "Rock": ["general", "nature", "powerful", "grey", "brown", "black", "pale"],
        "Rook": ["general", "edgy", "nature", "grey", "black"],
        "Root": ["general", "nature", "powerful"],
        "Rose": ["general", "edgy", "nature"],
        "Rowan": ["general", "nature", "powerful", "brown", "red", "orange"],
        "Rubble": ["general", "nature"],
        "Running": ["general"],
        "Rush": ["general", "powerful"],
        "Rye": ["general", "nature"],
        "Russet": ["general", "edgy", "powerful", "red", "brown"],
        "Sage": ["general", "nature"],
        "Sand": ["general", "nature", "pale", "yellow", "white", "cream"],
        "Scorch": ["general", "edgy", "powerful"],
        "Scourge": ["general", "edgy", "powerful"],
        "Scowl": ["general", "edgy"],
        "Scrap": ["general", "edgy"],
        "Scree": ["general", "nature"],
        "Sedge": ["general", "nature"],
        "Seed": ["general", "nature"],
        "Shade": ["general", "edgy", "nature", "grey", "black"],
        "Shadow": ["general", "edgy", "nature", "powerful", "grey", "black"],
        "Sharp": ["general", "powerful"],
        "Sheep": ["general", "nature", "white", "cream", "pale"],
        "Shell": ["general", "nature"],
        "Shimmer": ["general"],
        "Shine": ["general"],
        "Shining": ["general"],
        "Shiver": ["general"],
        "Short": ["general"],
        "Shred": ["general", "edgy", "powerful"],
        "Shrew": ["general", "nature"],
        "Shy": ["general"],
        "Silt": ["general", "nature"],
        "Silver": ["general", "edgy", "grey"],
        "Skip": ["general"],
        "Sky": ["general", "nature"],
        "Slash": ["general", "edgy", "powerful"],
        "Slate": ["general", "edgy", "nature", "grey"],
        "Sleek": ["general", "edgy"],
        "Slight": ["general"],
        "Sloe": ["general", "nature"],
        "Small": ["general"],
        "Smoke": ["general", "edgy", "nature", "grey", "black"],
        "Smudge": ["general"],
        "Snail": ["general", "nature"],
        "Snake": ["general", "edgy", "nature"],
        "Snap": ["general", "edgy", "powerful"],
        "Snapper": ["general", "nature"],
        "Sneeze": ["general"],
        "Snip": ["general"],
        "Snow": ["general", "nature", "white", "pale", "cream"],
        "Soft": ["general"],
        "Song": ["general"],
        "Sorrel": ["general", "nature"],
        "Spark": ["general"],
        "Sparrow": ["general", "nature"],
        "Speckle": ["general", "tortoise", "calico"],
        "Spider": ["general", "edgy", "nature"],
        "Spike": ["general", "edgy", "powerful"],
        "Spire": ["general", "powerful"],
        "Splash": ["general", "nature"],
        "Splinter": ["general", "edgy", "nature"],
        "Spot": ["general"],
        "Spotted": ["general"],
        "Stag": ["general", "nature", "powerful"],
        "Starling": ["general", "nature"],
        "Stem": ["general", "nature"],
        "Stoat": ["general", "nature"],
        "Stone": ["general", "nature", "powerful", "grey", "black", "brown"],
        "Stork": ["general", "nature"],
        "Storm": ["general", "edgy", "nature", "powerful"],
        "Streak": ["general", "edgy", "powerful"],
        "Stream": ["general", "nature"],
        "Strike": ["general", "edgy", "powerful"],
        "Stripe": ["general"],
        "Strong": ["general", "powerful"],
        "Sun": ["general", "nature", "yellow", "pale", "cream"],
        "Sunny": ["general", "nature", "yellow", "pale", "cream"],
        "Swallow": ["general", "nature"],
        "Swamp": ["general", "edgy", "nature"],
        "Swan": ["general", "nature"],
        "Sweet": ["general"],
        "Swift": ["general", "powerful"],
        "Swoop": ["general", "powerful"],
        "Tall": ["general"],
        "Talon": ["general", "edgy", "nature", "powerful"],
        "Tangle": ["general", "edgy", "nature"],
        "Tansy": ["general", "nature"],
        "Tawny": ["general", "brown", "red", "calico", "tortoise"],
        "Tempest": ["general", "edgy", "nature", "powerful"],
        "Thistle": ["general", "edgy", "nature", "powerful"],
        "Thorn": ["general", "edgy", "nature", "powerful"],
        "Thrift": ["general"],
        "Thrush": ["general", "nature"],
        "Thunder": ["general", "edgy", "nature", "powerful"],
        "Timber": ["general", "nature", "powerful"],
        "Tiny": ["general"],
        "Toad": ["general", "edgy", "nature"],
        "Torn": ["general", "powerful"],
        "Tree": ["general", "nature"],
        "Trout": ["general", "nature"],
        "Tulip": ["general", "nature"],
        "Tumble": ["general"],
        "Turtle": ["general", "nature"],
        "Tortoise": ["general", "nature"],
        "Twig": ["general", "nature"],
        "Twist": ["general", "powerful"],
        "Vine": ["general", "nature"],
        "Violet": ["general", "nature"],
        "Vixen": ["general", "nature", "red", "orange", "pale"],
        "Vole": ["general", "nature"],
        "Wander": ["general"],
        "Wasp": ["general", "edgy", "nature"],
        "Wave": ["general", "nature"],
        "Weasel": ["general", "edgy", "nature", "brown", "black"],
        "Web": ["general", "edgy"],
        "Wee": ["general"],
        "Wet": ["general"],
        "Whisker": ["general"],
        "Whisper": ["general", "edgy"],
        "Whistle": ["general"],
        "White": ["general", "white", "pale", "cream", "grey"],
        "Whorl": ["general"],
        "Wild": ["general", "nature", "powerful"],
        "Willow": ["general", "nature"],
        "Wind": ["general", "nature"],
        "Wish": ["general"],
        "Wolf": ["general", "edgy", "nature", "powerful", "grey", "brown", "black"],
        "Wood": ["general", "nature", "brown", "cream", "tortoise"],
        "Wooly": ["general"],
        "Wren": ["general", "nature"],
        "Yarrow": ["general", "nature"],
        "Yellow": ["general", "yellow", "cream", "pale"],
        "Yew": ["general", "nature"]
    }

names_suffix = [
    "bark",
    "beam",
    "bee",
    "belly",
    "berry",
    "bird",
    "blossom",
    "branch",
    "breeze",
    "briar",
    "bright",
    "brook",
    "burr",
    "claw",
    "cloud",
    "cone",
    "creek",
    "dapple",
    "dawn",
    "drop",
    "dusk",
    "dust",
    "ear",
    "eye",
    "face",
    "fall",
    "fang",
    "fawn",
    "feather",
    "fire",
    "flight",
    "flower",
    "fog",
    "foot",
    "frost",
    "fur",
    "gorse",
    "hawk",
    "haze",
    "heart",
    "leaf",
    "leap",
    "light",
    "mask",
    "mint",
    "mist",
    "mouse",
    "muzzle",
    "nose",
    "pelt",
    "petal",
    "pool",
    "poppy",
    "pounce",
    "puddle",
    "rain",
    "roar",
    "rose",
    "runner",
    "scar",
    "scratch",
    "shade",
    "shadow",
    "shine",
    "sight",
    "sky",
    "slip",
    "snow",
    "song",
    "speck",
    "speckle",
    "splash",
    "spot",
    "spots",
    "spring",
    "stem",
    "step",
    "stone",
    "storm",
    "stream",
    "stripe",
    "squeak",
    "swoop",
    "tail",
    "talon",
    "teeth",
    "thistle",
    "thorn",
    "throat",
    "toe",
    "tooth",
    "tuft",
    "vine",
    "water",
    "wave",
    "weed",
    "whisker",
    "whisper",
    "whistle",
    "willow",
    "wing",
    "wish"
]

banned = [
    "Fireheart",
    "Squirrelflight",
    "Alderheart",
    "Ivypool",
    "Dovewing",
    "Jayfeather"
]